# Generated by Django 5.1.3 on 2024-11-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
