# Generated by Django 5.1.3 on 2024-12-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_phone_number_userprofile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='ali@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
