# Generated by Django 5.1.3 on 2024-11-25 06:15

import django.db.models.deletion
import iranian_cities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0001_initial'),
        ('iranian_cities', '0004_remove_abadi_shhahr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireinsurance',
            name='County',
            field=iranian_cities.fields.ShahrField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahr'),
        ),
        migrations.AlterField(
            model_name='fireinsurance',
            name='city',
            field=iranian_cities.fields.OstanField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.ostan'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='County',
        ),
    ]
