# Generated by Django 5.1.3 on 2024-11-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0002_alter_fireinsurance_county_alter_fireinsurance_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fireinsurance',
            old_name='city',
            new_name='ostan',
        ),
        migrations.RenameField(
            model_name='fireinsurance',
            old_name='County',
            new_name='shahr',
        ),
    ]
