# Generated by Django 5.1.3 on 2024-11-25 07:10

import django.db.models.deletion
import iranian_cities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0003_rename_city_fireinsurance_ostan_and_more'),
        ('iranian_cities', '0004_remove_abadi_shhahr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireinsurance',
            name='Number_Of_Units',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fireinsurance',
            name='shahr',
            field=iranian_cities.fields.ShahrestanField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahrestan'),
        ),
    ]
