# Generated by Django 5.1.3 on 2024-11-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0004_alter_fireinsurance_number_of_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileinsurance',
            name='City',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileinsurance',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mobileinsurance',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileinsurance',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mobileinsurance',
            name='national_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileinsurance',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobileinsurance',
            name='price',
            field=models.IntegerField(),
        ),
    ]
