# Generated by Django 5.1.3 on 2024-12-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0008_fireinsurance_exact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireinsurance',
            name='Expiration_date_previous_insurance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fireinsurance',
            name='name_family',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
