# Generated by Django 5.1.3 on 2024-12-14 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0010_sold'),
        ('accounts', '0009_alter_userprofile_email_alter_userprofile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('fire', 'بیمه آتش\u200cسوزی'), ('mobile', 'بیمه موبایل')], default='fire', max_length=10)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='sold',
        ),
        migrations.AddField(
            model_name='fireinsurance',
            name='insurance_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fire_insurances', to='Insurance.insurancecompany'),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mobileinsurance',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_insurances', to='Insurance.insurancecompany'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='fire_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='Insurance.fireinsurance'),
        ),
        migrations.AddField(
            model_name='sale',
            name='mobile_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='Insurance.mobileinsurance'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.userprofile'),
        ),
    ]
