# Generated by Django 5.1.3 on 2024-12-14 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0011_sale_delete_sold_fireinsurance_insurance_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireinsurance',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fire_insurances', to='Insurance.insurancecompany'),
        ),
    ]
