# Generated by Django 5.1.3 on 2024-12-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0012_alter_fireinsurance_insurance_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancecompany',
            old_name='established_date',
            new_name='established',
        ),
    ]
