# Generated by Django 5.1.3 on 2024-12-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance', '0013_rename_established_date_insurancecompany_established'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fireinsurance',
            name='insurance_company',
        ),
        migrations.RemoveField(
            model_name='mobileinsurance',
            name='insurance_company',
        ),
    ]
